name: Code Quality

on:
  pull_request:
    paths:
      - "powersearch.py"
  push:
    paths:
      - "powersearch.py"
  workflow_dispatch:
    paths:
      - "powersearch.py"

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v1
        with:
          checkName: "Python Lint"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
